// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// FmeasureC
double FmeasureC(NumericVector pred, NumericVector ref);
RcppExport SEXP cytometree_FmeasureC(SEXP predSEXP, SEXP refSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ref(refSEXP);
    __result = Rcpp::wrap(FmeasureC(pred, ref));
    return __result;
END_RCPP
}
// FmeasureC_no0
double FmeasureC_no0(NumericVector pred, NumericVector ref);
RcppExport SEXP cytometree_FmeasureC_no0(SEXP predSEXP, SEXP refSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ref(refSEXP);
    __result = Rcpp::wrap(FmeasureC_no0(pred, ref));
    return __result;
END_RCPP
}
