// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// FmeasureC
double FmeasureC(NumericVector pred, NumericVector ref);
RcppExport SEXP Cytometree_FmeasureC(SEXP predSEXP, SEXP refSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ref(refSEXP);
    __result = Rcpp::wrap(FmeasureC(pred, ref));
    return __result;
END_RCPP
}
// FmeasureC_no0
double FmeasureC_no0(NumericVector pred, NumericVector ref);
RcppExport SEXP Cytometree_FmeasureC_no0(SEXP predSEXP, SEXP refSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ref(refSEXP);
    __result = Rcpp::wrap(FmeasureC_no0(pred, ref));
    return __result;
END_RCPP
}
// Fmeasure_costC
List Fmeasure_costC(NumericMatrix c);
RcppExport SEXP Cytometree_Fmeasure_costC(SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type c(cSEXP);
    __result = Rcpp::wrap(Fmeasure_costC(c));
    return __result;
END_RCPP
}
// Fmeasure_costC_arma
List Fmeasure_costC_arma(arma::mat c);
RcppExport SEXP Cytometree_Fmeasure_costC_arma(SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type c(cSEXP);
    __result = Rcpp::wrap(Fmeasure_costC_arma(c));
    return __result;
END_RCPP
}
// mvnpdfC
NumericVector mvnpdfC(NumericVector x, double mean, double var, bool Log);
RcppExport SEXP Cytometree_mvnpdfC(SEXP xSEXP, SEXP meanSEXP, SEXP varSEXP, SEXP LogSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type var(varSEXP);
    Rcpp::traits::input_parameter< bool >::type Log(LogSEXP);
    __result = Rcpp::wrap(mvnpdfC(x, mean, var, Log));
    return __result;
END_RCPP
}
// nmixpdfC
NumericVector nmixpdfC(NumericVector x, NumericVector mu, NumericVector Sigma, NumericVector Pi, bool Log);
RcppExport SEXP Cytometree_nmixpdfC(SEXP xSEXP, SEXP muSEXP, SEXP SigmaSEXP, SEXP PiSEXP, SEXP LogSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Pi(PiSEXP);
    Rcpp::traits::input_parameter< bool >::type Log(LogSEXP);
    __result = Rcpp::wrap(nmixpdfC(x, mu, Sigma, Pi, Log));
    return __result;
END_RCPP
}
