# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C++ implementation of the F-measure computation
#' 
#'@param pred vector of a predicted partition
#'@param ref vector of a reference partition
#'
#'@export
#'
FmeasureC <- function(pred, ref) {
    .Call('cytometree_FmeasureC', PACKAGE = 'cytometree', pred, ref)
}

#' C++ implementation of the F-measure computation without the ref classe 0
#' 
#' Aghaeepour in FlowCAP 1 ignore the reference class labeled "0"
#' 
#' 
#'@param pred vector of a predicted partition
#'@param ref vector of a reference partition
#'
#'@export
#'
FmeasureC_no0 <- function(pred, ref) {
    .Call('cytometree_FmeasureC_no0', PACKAGE = 'cytometree', pred, ref)
}

mvnpdfC <- function(x, mean, var, Log = TRUE) {
    .Call('cytometree_mvnpdfC', PACKAGE = 'cytometree', x, mean, var, Log)
}

nmixpdfC <- function(x, mu, Sigma, Pi, Log = TRUE) {
    .Call('cytometree_nmixpdfC', PACKAGE = 'cytometree', x, mu, Sigma, Pi, Log)
}

