# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C++ implementation of the F-measure computation
#' 
#'@param pred vector of a predicted partition
#'@param ref vector of a reference partition
#'
#'@export
#'
#'@examples
#'c <- list(c(1,1,2,3,2,3), c(1,1,1,2,3,3),c(2,2,1,1,1,1))
#'similarityMatC(sapply(c, "["))
#'
#'c2 <- list()
#'for(i in 1:100){
#'     c2 <- c(c2, list(rmultinom(n=1, size=3000, prob=rexp(n=3000))))
#'}
#'library(microbenchmark)
#'f <- function(){c3 <-sapply(c2, "[")
#'             similarityMatC(c3)}
#'microbenchmark(f(), time=1L)
#'
FmeasureC <- function(pred, ref) {
    .Call('Cytometree_FmeasureC', PACKAGE = 'Cytometree', pred, ref)
}

#' C++ implementation of the F-measure computation without the ref classe 0
#' 
#' Aghaeepour in FlowCAP 1 ignore the reference class labeled "0"
#' 
#' 
#'@param pred vector of a predicted partition
#'@param ref vector of a reference partition
#'
#'@export
#'
#'@examples
#'c <- list(c(1,1,2,3,2,3), c(1,1,1,2,3,3),c(2,2,1,1,1,1))
#'similarityMatC(sapply(c, "["))
#'
#'c2 <- list()
#'for(i in 1:100){
#'     c2 <- c(c2, list(rmultinom(n=1, size=3000, prob=rexp(n=3000))))
#'}
#'library(microbenchmark)
#'f <- function(){c3 <-sapply(c2, "[")
#'             similarityMatC(c3)}
#'microbenchmark(f(), time=1L)
#'
FmeasureC_no0 <- function(pred, ref) {
    .Call('Cytometree_FmeasureC_no0', PACKAGE = 'Cytometree', pred, ref)
}

#' C++ implementation of cost computation with Fmeasure as loss function
#' 
#'
#'@param c matrix where each column is one MCMC partition
#'
#'@export
#'
#'@examples
#'c <- list(c(1,1,2,3,2,3), c(1,1,1,2,3,3),c(2,2,1,1,1,1))
#'Fmeasure_costC(sapply(c, "["))
#'
#'c2 <- list()
#'for(i in 1:500){
#'     c2 <- c(c2, list(rmultinom(n=1, size=10000, prob=rexp(n=10000))))
#'}
#'library(microbenchmark)
#'f <- function(){c3 <-sapply(c2, "[")
#'             Fmeasure_costC(c3)}
#'fa <- function(){c3 <-sapply(c2, "[")
#'             Fmeasure_costC_arma(c3)}
#'microbenchmark(f(), fa(), times=10L)
#'
Fmeasure_costC <- function(c) {
    .Call('Cytometree_Fmeasure_costC', PACKAGE = 'Cytometree', c)
}

#' C++ implementation of cost computation with Fmeasure as loss function
#' using the Armadillo library
#' 
#'
#'@param c matrix where each column is one partition
#'
#'@export
Fmeasure_costC_arma <- function(c) {
    .Call('Cytometree_Fmeasure_costC_arma', PACKAGE = 'Cytometree', c)
}

mvnpdfC <- function(x, mean, var, Log = TRUE) {
    .Call('Cytometree_mvnpdfC', PACKAGE = 'Cytometree', x, mean, var, Log)
}

nmixpdfC <- function(x, mu, Sigma, Pi, Log = TRUE) {
    .Call('Cytometree_nmixpdfC', PACKAGE = 'Cytometree', x, mu, Sigma, Pi, Log)
}

